export const USER_SET_AVATAR_ID = "USER_SET_AVATAR_ID";
export const USER_SET_FAST_AUTH_PENDING_TIME =
  "USER_SET_FAST_AUTH_PENDING_TIME";
export const USER_SET_FAST_AUTH_REJECTED_TIME =
  "USER_SET_FAST_AUTH_REJECTED_TIME";
export const USER_SET_FAST_AUTH_REQUIRED = "USER_SET_FAST_AUTH_REQUIRED";
export const USER_SET_FAST_AUTH_STATUS = "USER_SET_FAST_AUTH_STATUS";
export const USER_SET_PERMISSIONS = "USER_SET_PERMISSIONS";
export const USER_SET_USER = "USER_SET_USER";

export const BACK_URL = "USER_SET_USER";
